from time import sleep

def desenha_jogo(erros, jogador):
    if erros == 0:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|      ')
        print('|      ')
        print('|      ')
        print('|      ')
    elif erros == 1:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|      ')
        print('|      ')
        print('|      ')
        print('Você errou tente outra letra! ')
    elif erros == 2:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|    | ')
        print('|      ')
        print('|      ')
        print('Você errou tente outra letra! ')
    elif erros == 3:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|   /| ')
        print('|      ')
        print('|      ')
        print('Você errou tente outra letra! ')
    elif erros == 4:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|   /|\ ')
        print('|      ')
        print('|      ')
        print('Você errou tente outra letra! ')
    elif erros == 5:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|   /|\ ')
        print('|    | ')
        print('|      ')
        print('Você errou tente outra letra! ')
    elif erros == 6:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|   /|\ ')
        print('|    | ')
        print('|   /  ')
        print('Você errou tente outra letra! ')
    elif erros == 7:
        print(f'Pontos partida: {jogador.get("pontos")}')
        print(f'Erros: {erros}')
        print()
        print('|----- ')
        print('|    | ')
        print('|    Q ')
        print('|   /|\ ')
        print('|    | ')
        print('|   / \ ')
        print('Sinto lhe informar mas... ')
        print('VOCÊ PERDEU!! ')

def divisoes():
    print('-' * 40)

def exibe_palavra(letra, palavra_certa, letras_acertou):
    for letra in palavra_certa:
        if letra in letras_acertou:
            print(letra, end=' ')
        else:
            print('_', end=' ')
    print()

def mostrar_regras():
    print('-=' * 19)
    print(f'''{'-=' * 8}REGRAS{'-=' * 8}''')
    print('-=' * 19)
    print('Neste jogo seu objetivo é adivinhar qual é a palavra.')
    print('Para isso você tem 7 vidas, cada vez que errar perde uma delas.')
    print('Ao perder todas elas você perde a rodada, se descobrir a palavra você pode chutar.')
    print('Mas se errar perde a rodada!')
    sleep(6)